#!/usr/bin/env python3
import requests
import lastfm
import lastfm2
import lastfm3 # New Import
import lastfm4

USER = "zector1981"
API_KEY = "06706dd5607746739fbd1ed356d6ad42"
URL = f"https://ws.audioscrobbler.com/2.0/?method=user.getrecenttracks&user={USER}&api_key={API_KEY}&format=json&limit=200"

def main():
    try:
        print(f"📡 Fetching Recent Activity for {USER}...")
        r = requests.get(URL)
        json_payload = r.json()

        print("=" * 40)
        lastfm.get_stats(json_payload)  # Diversity & Totals
        
        print("-" * 40)
        lastfm2.get_bulls(json_payload) # The 50 vs 150 Trend
        
        print("-" * 40)
        # We call the new Weekly script here
        lastfm3.get_weekly_champ(USER, API_KEY) 
        print("=" * 40)

        print("-" * 40)
        # Pull the last 5 weeks of champions
        lastfm4.get_weekly_history(USER, API_KEY, limit=5)
        print("=" * 40)

    except Exception as e:
        print(f"Manager Error: {e}")

if __name__ == "__main__":
    main()
